In [5]:
#全部行都能输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import scaleale

In [6]:
data = pd.read_excel(r'data.xlsx')    #读取数据
data

年份      X1     X2     X3     X4       X5     X6
0   2003  101.17  21124  11.00  35.34   494173  13361
1   2004  103.88  19590  11.96  36.07   648493  14927
2   2005  101.81  21124  11.71  44.42   763030  16245
3   2006  101.47  25326  13.00  40.75   536231  17957
4   2007  104.77  28767  14.39  42.29  1037069  18943
5   2008  105.86  31854  14.52  43.59  1351088  20110
6   2009   99.31  32491  16.03  50.52  1558313  20399
7   2010  103.32  35824  16.01  51.54  1773305  22784
8   2011  105.39  37664  16.37  50.14  2016029  23690
9   2012  102.65  44848  18.13  52.23  2354265  24944
10  2013  102.62  55508  20.97  51.60  2781072  26054
11  2014  101.99  52267  20.21  54.37  3075821  26650
12  2015  101.44  53361  18.88  58.21  2597340  27621
13  2016  102.00  56086  18.46  59.64  2447120  27939
14  2017  101.56  61271  18.05  59.30  2371155  29717

In [13]:
data_zscore = data.iloc[:,1:].apply(lambda x:(x - np.mean(x)) / np.std(x))    #数据标准化
data_zscore
data_cor = np.corrcoef(np.transpose(data_zscore))                              #协方差矩阵
data_cor

X1        X2        X3        X4        X5        X6
0  -0.852007 -1.250892 -1.634839 -1.744293 -1.446624 -1.766769
1   0.744769 -1.361492 -1.319647 -1.648750 -1.264553 -1.449786
2  -0.474908 -1.250892 -1.401729 -0.555895 -1.129418 -1.183001
3  -0.675242 -0.947932 -0.978189 -1.036228 -1.397003 -0.836465
4   1.269172 -0.699840 -0.521818 -0.834671 -0.806098 -0.636882
5   1.911418 -0.477271 -0.479136 -0.664526 -0.435608 -0.400663
6  -1.947949 -0.431344  0.016635  0.242479 -0.191118 -0.342164
7   0.414808 -0.191038  0.010069  0.375977  0.062537  0.140598
8   1.634486 -0.058376  0.128266  0.192744  0.348910  0.323987
9   0.020033  0.459582  0.706118  0.466285  0.747972  0.577817
10  0.002357  1.228157  1.638560  0.383830  1.251532  0.802499
11 -0.368849  0.994484  1.389033  0.746370  1.599287  0.923139
12 -0.692918  1.073360  0.952361  1.248953  1.034760  1.119685
13 -0.362957  1.269830  0.814465  1.436112  0.857525  1.184054
14 -0.622212  1.643663  0.679852  1.391613  0.767899  1.543950

array([[ 1.        , -0.16207044, -0.10221926, -0.24177031, -0.07965189,
        -0.08405906],
       [-0.16207044,  1.        ,  0.9327899 ,  0.91316227,  0.93490022,
         0.97384568],
       [-0.10221926,  0.9327899 ,  1.        ,  0.86045697,  0.97741763,
         0.92834918],
       [-0.24177031,  0.91316227,  0.86045697,  1.        ,  0.88704857,
         0.956038  ],
       [-0.07965189,  0.93490022,  0.97741763,  0.88704857,  1.        ,
         0.93609634],
       [-0.08405906,  0.97384568,  0.92834918,  0.956038  ,  0.93609634,
         1.        ]])

In [12]:
pca = PCA()
pca.fit(data_zscore)
pca.components_                    #主成分载荷
pca.explained_variance_ratio_      #主成分贡献率

PCA()

array([[ 0.07946079, -0.44957708, -0.44328887, -0.43773953, -0.4463166 ,
        -0.45193695],
       [-0.98460687, -0.00767771, -0.07656078,  0.09122839, -0.09751945,
        -0.0824387 ],
       [-0.1155802 , -0.0420622 ,  0.56294841, -0.63256442,  0.40688775,
        -0.31979008],
       [-0.0227194 ,  0.75580727, -0.12617413, -0.49186202, -0.36076678,
         0.20059504],
       [-0.00224838, -0.26696366,  0.64152022,  0.02403757, -0.6659711 ,
         0.27033654],
       [ 0.10176089,  0.39183931,  0.23076917,  0.39675897, -0.22817458,
        -0.75721261]])

array([0.79076401, 0.16637699, 0.02725403, 0.01118303, 0.00349356,
       0.00092838])

In [15]:
pca = PCA(2)
pca.fit(data_zscore)
data_low = pca.transform(data_zscore)       #主成分得分
data_low

PCA(n_components=2)

array([[ 3.42704402,  1.10125549],
       [ 3.19758591, -0.5293947 ],
       [ 2.42806344,  0.74147142],
       [ 2.26126642,  0.8576754 ],
       [ 1.65977151, -1.1493433 ],
       [ 1.24523091, -1.8267611 ],
       [ 0.1655557 ,  1.98896864],
       [-0.14164876, -0.39111675],
       [-0.28725451, -1.66184919],
       [-1.31712045, -0.15535231],
       [-2.36759565, -0.29038903],
       [-2.54985397,  0.08521704],
       [-2.47436263,  0.52182316],
       [-2.50725884,  0.23504178],
       [-2.73942312,  0.47275345]])